In [3]:
pip install pandas

Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

# Series is A single column of data with an associated index Typically holds a single data type (e.g., all integers, all strings, etc.), Pandas  is A table with rows and multiple columns, each with an associated index Can hold multiple data types (each column can have a different type)

In [5]:
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
Series1 = pd.Series(data , index = index)
Series1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
    })
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [7]:
obesity_data = pd.read_csv('./obesity_prediction.csv')

In [8]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [9]:
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [10]:
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [11]:
obesity_data.head(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight

In [12]:
obesity_data.tail(15)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2096,Female,25.955014,1.626449,104.879602,yes,yes,3.0,3.0,Sometimes,no,2.094901,no,0.070890,0.599441,Sometimes,Public_Transportation,Obesity_Type_III
2097,Female,25.996716,1.626580,105.037203,yes,yes,3.0,3.0,Sometimes,no,2.347322,no,0.008013,0.503896,Sometimes,Public_Transportation,Obesity_Type_III
2098,Female,25.992348,1.606474,104.954291,yes,yes,3.0,3.0,Sometimes,no,2.331123,no,0.063383,0.561661,Sometimes,Public_Transportation,Obesity_Type_III
2099,Female,25.974446,1.628855,108.090006,yes,yes,3.0,3.0,Sometimes,no,1.757105,no,0.085119,0.465444,Sometimes,Public_Transportation,Obesity_Type_III
2100,Female,25.777565,1.628205,107.378702,yes,yes,3.0,3.0,Sometimes,no,2.506631,no,0.025787,0.484165,Sometimes,Public_Transportation,Obesity_Type_III
2101,Female,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III
2102,Female,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246,0.413106,Sometimes,Public_Transportation,Obesity_Type_III
2103,Female,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation,Obesity_Type_III
2104,Female,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398,0.931455,Sometimes,Public_Transportation,Obesity_Type_III
2105,Female,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332,0.897924,Sometimes,Public_Transportation,Obesity_Type_III
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [13]:
obesity_data.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history', 'FAVC', 'FCVC',
       'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS',
       'Obesity'],
      dtype='object')

In [14]:
obesity_data.sample(5)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1682,Male,37.997912,1.760710,118.668332,yes,yes,2.611222,2.992083,Sometimes,no,1.796376,no,0.641954,0.202810,Sometimes,Automobile,Obesity_Type_II
1961,Female,26.000000,1.613574,107.012256,yes,yes,3.000000,3.000000,Sometimes,no,2.678779,no,0.000000,0.508848,Sometimes,Public_Transportation,Obesity_Type_III
640,Female,20.172661,1.605521,44.661461,no,no,3.000000,2.893778,Frequently,no,1.000000,yes,0.769726,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
1520,Male,34.139453,1.774647,120.151967,yes,no,2.962415,3.000000,Sometimes,no,2.172649,no,1.097905,0.000000,Sometimes,Automobile,Obesity_Type_II
174,Male,21.000000,1.620000,70.000000,no,yes,2.000000,1.000000,no,no,3.000000,no,1.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_I

In [15]:
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [16]:
obesity_data.sample(5, random_state=42)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
544,Female,20.406871,1.755978,53.699561,yes,yes,2.0,3.891994,Frequently,no,1.863930,no,2.870127,2.000000,no,Public_Transportation,Insufficient_Weight
1987,Female,26.000000,1.624950,111.004920,yes,yes,3.0,3.000000,Sometimes,no,2.704315,no,0.000000,0.322666,Sometimes,Public_Transportation,Obesity_Type_III
420,Male,18.000000,1.850000,60.000000,yes,yes,3.0,4.000000,Sometimes,no,2.000000,yes,2.000000,0.000000,Sometimes,Automobile,Insufficient_Weight
527,Female,21.000000,1.520000,42.000000,no,yes,3.0,1.000000,Frequently,no,1.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
196,Male,22.000000,1.750000,74.000000,yes,no,2.0,3.000000,Sometimes,no,2.000000,no,1.000000,2.000000,Sometimes,Bike,Normal_Weight

In [17]:
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [18]:
obesity_data.loc[0]

Gender                           Female
Age                                21.0
Height                             1.62
Weight                             64.0
family_history                      yes
FAVC                                 no
FCVC                                2.0
NCP                                 3.0
CAEC                          Sometimes
SMOKE                                no
CH2O                                2.0
SCC                                  no
FAF                                 0.0
TUE                                 1.0
CALC                                 no
MTRANS            Public_Transportation
Obesity                   Normal_Weight
Name: 0, dtype: object

In [19]:
obesity_data.loc[0:10,'Age':'TUE']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0
5,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0
6,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0
7,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0

In [20]:
obesity_data.loc[:,:'CAEC']

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes
...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes

In [21]:
obesity_data.loc[2100:, 'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
2100,25.777565,1.628205,107.378702,yes,yes,3.0,3.0,Sometimes,no,2.506631,no,0.025787
2101,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329
2102,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246
2103,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639
2104,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398
2105,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332
2106,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269
2107,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390
2108,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209
2109,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107
2110,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452

In [22]:
obesity_data.iloc[0:10, 0:5]

   Gender   Age  Height  Weight family_history
0  Female  21.0    1.62    64.0            yes
1  Female  21.0    1.52    56.0            yes
2    Male  23.0    1.80    77.0            yes
3    Male  27.0    1.80    87.0             no
4    Male  22.0    1.78    89.8             no
5    Male  29.0    1.62    53.0             no
6  Female  23.0    1.50    55.0            yes
7    Male  22.0    1.64    53.0             no
8    Male  24.0    1.78    64.0            yes
9    Male  22.0    1.72    68.0            yes

In [23]:
obesity_data.iloc[:, 0:5]

      Gender        Age    Height      Weight family_history
0     Female  21.000000  1.620000   64.000000            yes
1     Female  21.000000  1.520000   56.000000            yes
2       Male  23.000000  1.800000   77.000000            yes
3       Male  27.000000  1.800000   87.000000             no
4       Male  22.000000  1.780000   89.800000             no
...      ...        ...       ...         ...            ...
2106  Female  20.976842  1.710730  131.408528            yes
2107  Female  21.982942  1.748584  133.742943            yes
2108  Female  22.524036  1.752206  133.689352            yes
2109  Female  24.361936  1.739450  133.346641            yes
2110  Female  23.664709  1.738836  133.472641            yes

[2111 rows x 5 columns]

In [24]:
obesity_data.iloc[0:10]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight

In [25]:
obesity_data.iloc[[10, 20, 30], [0,1,2]]

   Gender   Age  Height
10   Male  26.0    1.85
20   Male  22.0    1.65
30   Male  29.0    1.77

In [26]:
obesity_data.at[0, 'Age']

np.float64(21.0)

In [27]:
obesity_data.iat[0, 5]

'no'

In [28]:
obesity_data[['Age', 'Height', 'Weight']]

            Age    Height      Weight
0     21.000000  1.620000   64.000000
1     21.000000  1.520000   56.000000
2     23.000000  1.800000   77.000000
3     27.000000  1.800000   87.000000
4     22.000000  1.780000   89.800000
...         ...       ...         ...
2106  20.976842  1.710730  131.408528
2107  21.982942  1.748584  133.742943
2108  22.524036  1.752206  133.689352
2109  24.361936  1.739450  133.346641
2110  23.664709  1.738836  133.472641

[2111 rows x 3 columns]

In [29]:
obesity_data.loc[obesity_data['Height']>1]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [30]:
obesity_data.loc[obesity_data['Weight']<50]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.000000,1.560000,49.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,yes,2.000000,0.000000,no,Walking,Normal_Weight
37,Female,21.000000,1.600000,48.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,1.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.000000,1.500000,44.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
60,Female,21.000000,1.550000,49.000000,yes,yes,2.000000,3.000000,Sometimes,no,3.000000,no,3.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
75,Female,23.000000,1.630000,45.000000,yes,no,3.000000,3.000000,Sometimes,no,3.000000,yes,2.000000,0.000000,no,Public_Transportation,Insufficient_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Female,19.269079,1.580920,44.753943,no,no,3.000000,2.975362,Frequently,no,1.246822,yes,0.979701,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
738,Female,19.946244,1.603435,45.000000,no,no,3.000000,3.000000,Frequently,no,2.487919,yes,1.230441,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
739,Female,19.639431,1.535350,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.496810,no,0.000000,0.513427,Sometimes,Public_Transportation,Insufficient_Weight
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight

In [31]:
obesity_data.loc[(obesity_data['Weight']<50) & (obesity_data['Obesity'] == 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.0,1.56,49.0,no,yes,2.0,3.0,Sometimes,no,1.0,yes,2.0,0.0,no,Walking,Normal_Weight
37,Female,21.0,1.60,48.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.0,1.50,44.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
60,Female,21.0,1.55,49.0,yes,yes,2.0,3.0,Sometimes,no,3.0,no,3.0,1.0,Sometimes,Public_Transportation,Normal_Weight
94,Female,24.0,1.60,48.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
113,Female,22.0,1.50,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Walking,Normal_Weight
156,Female,35.0,1.53,45.0,yes,no,3.0,3.0,Frequently,no,1.0,no,0.0,1.0,no,Automobile,Normal_Weight
176,Female,18.0,1.57,48.0,yes,yes,3.0,1.0,Always,no,1.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
180,Female,18.0,1.58,48.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
218,Female,21.0,1.50,42.3,yes,no,1.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Public_Transportation,Normal_Weight
234,Female,19.0,1.59,49.0,yes,yes,2.0,1.0,no,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
244,Female,21.0,1.54,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,yes,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
253,Female,26.0,1.59,47.0,yes,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
303,Female,16.0,1.57,49.0,no,yes,2.0,4.0,Always,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
307,Female,23.0,1.59,48.0,yes,yes,2.0,1.0,Frequently,no,1.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
318,Female,25.0,1.56,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
346,Female,21.0,1.54,47.0,yes,no,3.0,3.0,Always,no,1.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
359,Female,33.0,1.56,48.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
385,Female,16.0,1.55,45.0,no,yes,2.0,3.0,Frequently,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
445,Female,19.0,1.51,45.0,no,yes,2.0,4.0,Sometimes,no,1.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
457,Female,19.0,1.50,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [32]:
obesity_data.loc[(obesity_data['Weight']<50) | (obesity_data['Obesity'] == 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.000000,3.000000,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
5,Male,29.000000,1.620000,53.000000,no,yes,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
6,Female,23.000000,1.500000,55.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Female,19.269079,1.580920,44.753943,no,no,3.000000,2.975362,Frequently,no,1.246822,yes,0.979701,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
738,Female,19.946244,1.603435,45.000000,no,no,3.000000,3.000000,Frequently,no,2.487919,yes,1.230441,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
739,Female,19.639431,1.535350,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.496810,no,0.000000,0.513427,Sometimes,Public_Transportation,Insufficient_Weight
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight

In [33]:
obesity_data[obesity_data['Height']>1]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [34]:
obesity_data[(obesity_data['Weight']<50) | (obesity_data['Obesity'] == 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.000000,3.000000,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
5,Male,29.000000,1.620000,53.000000,no,yes,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
6,Female,23.000000,1.500000,55.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Female,19.269079,1.580920,44.753943,no,no,3.000000,2.975362,Frequently,no,1.246822,yes,0.979701,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
738,Female,19.946244,1.603435,45.000000,no,no,3.000000,3.000000,Frequently,no,2.487919,yes,1.230441,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
739,Female,19.639431,1.535350,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.496810,no,0.000000,0.513427,Sometimes,Public_Transportation,Insufficient_Weight
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight

In [37]:
obesity_data.loc[obesity_data['Obesity'].str.contains('Insufficient')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
59,Male,20.000000,1.760000,55.000000,yes,yes,2.000000,4.000000,Sometimes,no,3.000000,no,2.000000,2.000000,no,Public_Transportation,Insufficient_Weight
71,Female,22.000000,1.670000,50.000000,yes,no,3.000000,3.000000,no,no,3.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
75,Female,23.000000,1.630000,45.000000,yes,no,3.000000,3.000000,Sometimes,no,3.000000,yes,2.000000,0.000000,no,Public_Transportation,Insufficient_Weight
76,Female,24.000000,1.600000,45.000000,yes,no,2.000000,3.000000,no,no,2.000000,no,1.000000,0.000000,no,Public_Transportation,Insufficient_Weight
83,Female,19.000000,1.600000,45.000000,no,no,3.000000,3.000000,no,no,3.000000,yes,2.000000,0.000000,no,Walking,Insufficient_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight
742,Male,18.000000,1.719827,52.289828,yes,yes,1.202075,3.000000,Sometimes,no,1.927976,no,0.023574,1.747256,Sometimes,Public_Transportation,Insufficient_Weight
743,Male,18.381382,1.722547,53.783977,yes,yes,2.000000,3.131032,Sometimes,no,2.072194,no,1.487987,2.000000,Sometimes,Public_Transportation,Insufficient_Weight
744,Male,18.000000,1.738702,50.248677,yes,yes,1.871213,3.000000,Sometimes,no,1.283738,no,0.684879,1.487223,Sometimes,Public_Transportation,Insufficient_Weight

In [38]:
obesity_data.loc[obesity_data['Obesity'].str.startswith('Insuff')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
59,Male,20.000000,1.760000,55.000000,yes,yes,2.000000,4.000000,Sometimes,no,3.000000,no,2.000000,2.000000,no,Public_Transportation,Insufficient_Weight
71,Female,22.000000,1.670000,50.000000,yes,no,3.000000,3.000000,no,no,3.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
75,Female,23.000000,1.630000,45.000000,yes,no,3.000000,3.000000,Sometimes,no,3.000000,yes,2.000000,0.000000,no,Public_Transportation,Insufficient_Weight
76,Female,24.000000,1.600000,45.000000,yes,no,2.000000,3.000000,no,no,2.000000,no,1.000000,0.000000,no,Public_Transportation,Insufficient_Weight
83,Female,19.000000,1.600000,45.000000,no,no,3.000000,3.000000,no,no,3.000000,yes,2.000000,0.000000,no,Walking,Insufficient_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight
742,Male,18.000000,1.719827,52.289828,yes,yes,1.202075,3.000000,Sometimes,no,1.927976,no,0.023574,1.747256,Sometimes,Public_Transportation,Insufficient_Weight
743,Male,18.381382,1.722547,53.783977,yes,yes,2.000000,3.131032,Sometimes,no,2.072194,no,1.487987,2.000000,Sometimes,Public_Transportation,Insufficient_Weight
744,Male,18.000000,1.738702,50.248677,yes,yes,1.871213,3.000000,Sometimes,no,1.283738,no,0.684879,1.487223,Sometimes,Public_Transportation,Insufficient_Weight

# Updating data using loc

In [39]:
obesity_data.loc[:,'Age'] *= 1.5

In [40]:
obesity_data

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.500000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,31.500000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,34.500000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,40.500000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,33.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,31.465263,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,32.974413,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,33.786054,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,36.542904,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,35.497063,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [41]:
obesity_data.loc[:, 'SMOKE'] = 'yes'

In [42]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,31.5,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,34.5,1.80,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.80,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [43]:
obesity_data.loc[[2,3], 'Height'] = 1.6

In [44]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,31.5,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [45]:
obesity_data.loc[:2, 'SMOKE'] = 'may be'

In [46]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,31.5,1.52,56.0,yes,no,3.0,3.0,Sometimes,may be,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [47]:
obesity_data.iloc[1,4] = 'no data'

In [48]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,may be,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [49]:
obesity_data.iloc[:,9] = 'doesn`t matter'

In [50]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [59]:
obesity_data.at[0,'Obesity'] = 'Overrrr Weight'
obesity_data.iat[2,1] = 34.5

In [60]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Not Preferred to say,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [61]:
obesity_data.iat[2,0] = "Not Preferred to say"

In [62]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Not Preferred to say,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [65]:
def increase_age_y10(row):
    return row + 10
obesity_data['Age'] = obesity_data['Age'].apply(increase_age_y10)
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,41.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight
1,Female,41.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Not Preferred to say,44.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,50.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,43.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [66]:
obesity_data['Age'] = obesity_data['Age'].apply(lambda x: x-10)
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Not Preferred to say,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [67]:
obesity_data['Age Category'] = obesity_data['Age'].apply(lambda x: "Young" if x<35 else "Not Young")
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [69]:
obesity_data['Age'] *= 2
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [74]:
import numpy as np
obesity_data['New Age Category'] = np.where(obesity_data['Age']<33, 'Very Young', 'Not So Young')
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,31.5,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young,Very Young
1,Female,31.5,1.52,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young,Very Young
2,Not Preferred to say,34.5,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young,Not So Young
3,Male,40.5,1.60,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young,Not So Young
4,Male,33.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young,Not So Young

In [75]:
BMI = obesity_data['Weight'] / (obesity_data['Height'] ** 2)
obesity_data.insert(3, 'BMI', BMI)
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,31.5,1.62,24.386526,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young,Very Young
1,Female,31.5,1.52,24.238227,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young,Very Young
2,Not Preferred to say,34.5,1.60,30.078125,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young,Not So Young
3,Male,40.5,1.60,33.984375,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young,Not So Young
4,Male,33.0,1.78,28.342381,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young,Not So Young

In [77]:
obesity_data.drop(columns=['New Age Category'], inplace=True)

In [78]:
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,31.5,1.62,24.386526,64.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,24.238227,56.0,no data,no,3.0,3.0,Sometimes,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,30.078125,77.0,yes,no,2.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,33.984375,87.0,no,no,3.0,3.0,Sometimes,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,28.342381,89.8,no,no,2.0,1.0,Sometimes,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [79]:
del obesity_data['CAEC']

In [80]:
obesity_data.head(20)

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,31.5,1.62,24.386526,64.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,30.078125,77.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,33.984375,87.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young
5,Male,43.5,1.62,20.195092,53.0,no,yes,2.0,3.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not Young
6,Female,34.5,1.50,24.444444,55.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Young
7,Male,33.0,1.64,19.705532,53.0,no,no,2.0,3.0,doesn`t matter,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
8,Male,36.0,1.78,20.199470,64.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Not Young
9,Male,33.0,1.72,22.985398,68.0,yes,yes,2.0,3.0,doesn`t matter,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Young
10,Male,39.0,1.85,30.679328,105.0,yes,yes,3.0,3.0,doesn`t matter,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,Not Young
11,Female,31.5,1.72,27.041644,80.0,yes,yes,2.0,3.0,doesn`t matter,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,Young
12,Male,33.0,1.65,20.569330,56.0,no,no,3.0,3.0,doesn`t matter,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
13,Male,61.5,1.80,30.555556,99.0,no,yes,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,Not Young
14,Male,34.5,1.77,19.151585,60.0,yes,yes,3.0,1.0,doesn`t matter,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Young
15,Female,33.0,1.70,22.837370,66.0,yes,no,3.0,3.0,doesn`t matter,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Young
16,Male,40.5,1.93,27.383285,102.0,yes,yes,2.0,1.0,doesn`t matter,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not Young
17,Female,43.5,1.53,33.320518,78.0,no,yes,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,Not Young
18,Female,45.0,1.71,28.042817,82.0,yes,yes,3.0,4.0,doesn`t matter,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,Not Young
19,Female,34.5,1.65,25.711662,70.0,yes,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,Young

In [81]:
obesity_data.rename(columns={'Obesity': 'Category', 'New Age Category' : 'reduntant info'}, inplace=True)

In [82]:
obesity_data.head(20)

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,31.5,1.62,24.386526,64.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,30.078125,77.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,33.984375,87.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young
5,Male,43.5,1.62,20.195092,53.0,no,yes,2.0,3.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not Young
6,Female,34.5,1.50,24.444444,55.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Young
7,Male,33.0,1.64,19.705532,53.0,no,no,2.0,3.0,doesn`t matter,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
8,Male,36.0,1.78,20.199470,64.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Not Young
9,Male,33.0,1.72,22.985398,68.0,yes,yes,2.0,3.0,doesn`t matter,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Young
10,Male,39.0,1.85,30.679328,105.0,yes,yes,3.0,3.0,doesn`t matter,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,Not Young
11,Female,31.5,1.72,27.041644,80.0,yes,yes,2.0,3.0,doesn`t matter,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,Young
12,Male,33.0,1.65,20.569330,56.0,no,no,3.0,3.0,doesn`t matter,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
13,Male,61.5,1.80,30.555556,99.0,no,yes,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,Not Young
14,Male,34.5,1.77,19.151585,60.0,yes,yes,3.0,1.0,doesn`t matter,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Young
15,Female,33.0,1.70,22.837370,66.0,yes,no,3.0,3.0,doesn`t matter,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Young
16,Male,40.5,1.93,27.383285,102.0,yes,yes,2.0,1.0,doesn`t matter,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not Young
17,Female,43.5,1.53,33.320518,78.0,no,yes,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,Not Young
18,Female,45.0,1.71,28.042817,82.0,yes,yes,3.0,4.0,doesn`t matter,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,Not Young
19,Female,34.5,1.65,25.711662,70.0,yes,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,Young

In [87]:
df1 = pd.DataFrame({
    'id' : [1,2,3,4],
    'name' : ['Keerti', 'Amit', 'Educosys', 'YouTube']
})

df2 = pd.DataFrame({
    'id' : [3,4, 5, 6],
    'course' : ['GenAI', 'CPP', 'HLD', 'LLD']
})

inner_result = pd.merge(df1, df2, how='inner', on='id')
inner_result

   id      name course
0   3  Educosys  GenAI
1   4   YouTube    CPP

In [88]:
outer_merge = pd.merge(df1, df2,  how='outer', on='id')
outer_merge

   id      name course
0   1    Keerti    NaN
1   2      Amit    NaN
2   3  Educosys  GenAI
3   4   YouTube    CPP
4   5       NaN    HLD
5   6       NaN    LLD

In [89]:
left_merge = pd.merge(df1, df2, how='left', on='id')
print(left_merge)

   id      name course
0   1    Keerti    NaN
1   2      Amit    NaN
2   3  Educosys  GenAI
3   4   YouTube    CPP

In [90]:
df3 = pd.DataFrame({
    'id1' : [1,2,3,4],
    'name' : ['Keerti', 'Amit', 'Educosys', 'YouTube']
})

df4 = pd.DataFrame({
    'id2' : [3,4, 5, 6],
    'course' : ['GenAI', 'CPP', 'HLD', 'LLD']
})

left_merge_diff_cols = pd.merge(df3, df4, how='left', left_on='id1', right_on='id2')
left_merge_diff_cols

   id1      name  id2 course
0    1    Keerti  NaN    NaN
1    2      Amit  NaN    NaN
2    3  Educosys  3.0  GenAI
3    4   YouTube  4.0    CPP

In [91]:
df1 = pd.DataFrame({
    'id' : [1,2,3,4],
    'name' : ['Keerti', 'Amit', 'Educosys', 'YouTube']
})

df2 = pd.DataFrame({
    'id' : [3,4, 5, 6],
    'course' : ['GenAI', 'CPP', 'HLD', 'LLD']
})

concat_result = pd.concat([df1, df2], axis=0, ignore_index=True)
concat_result

   id      name course
0   1    Keerti    NaN
1   2      Amit    NaN
2   3  Educosys    NaN
3   4   YouTube    NaN
4   3       NaN  GenAI
5   4       NaN    CPP
6   5       NaN    HLD
7   6       NaN    LLD

In [92]:
result2 = pd.concat([df1, df2], axis=1)
result2

   id      name  id course
0   1    Keerti   3  GenAI
1   2      Amit   4    CPP
2   3  Educosys   5    HLD
3   4   YouTube   6    LLD

In [93]:
result3 = pd.concat([df1, df2], axis=0, keys=['df1', 'df2'])
result3

       id      name course
df1 0   1    Keerti    NaN
    1   2      Amit    NaN
    2   3  Educosys    NaN
    3   4   YouTube    NaN
df2 0   3       NaN  GenAI
    1   4       NaN    CPP
    2   5       NaN    HLD
    3   6       NaN    LLD

In [94]:
result3.isna()

          id   name  course
df1 0  False  False    True
    1  False  False    True
    2  False  False    True
    3  False  False    True
df2 0  False   True   False
    1  False   True   False
    2  False   True   False
    3  False   True   False

In [95]:
result3.notna()

         id   name  course
df1 0  True   True   False
    1  True   True   False
    2  True   True   False
    3  True   True   False
df2 0  True  False    True
    1  True  False    True
    2  True  False    True
    3  True  False    True

In [96]:
result3.isna().sum()

id        0
name      4
course    4
dtype: int64

In [97]:
result3.notna().sum()

id        8
name      4
course    4
dtype: int64

In [98]:
obesity_data.loc[0, 'Age'] = np.nan
obesity_data.loc[3, 'Weight'] = np.nan
obesity_data.loc[5, 'family_history'] = np.nan

In [100]:
obesity_data.head(10)

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,NaN,1.62,24.386526,64.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,30.078125,77.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,33.984375,NaN,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young
5,Male,43.5,1.62,20.195092,53.0,NaN,yes,2.0,3.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not Young
6,Female,34.5,1.50,24.444444,55.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Young
7,Male,33.0,1.64,19.705532,53.0,no,no,2.0,3.0,doesn`t matter,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
8,Male,36.0,1.78,20.199470,64.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Not Young
9,Male,33.0,1.72,22.985398,68.0,yes,yes,2.0,3.0,doesn`t matter,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Young

In [101]:
obesity_data.fillna(0, inplace=True)

In [102]:
obesity_data.head(10)

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,0.0,1.62,24.386526,64.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,30.078125,77.0,yes,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,33.984375,0.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young
5,Male,43.5,1.62,20.195092,53.0,0,yes,2.0,3.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not Young
6,Female,34.5,1.50,24.444444,55.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Young
7,Male,33.0,1.64,19.705532,53.0,no,no,2.0,3.0,doesn`t matter,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
8,Male,36.0,1.78,20.199470,64.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Not Young
9,Male,33.0,1.72,22.985398,68.0,yes,yes,2.0,3.0,doesn`t matter,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Young

In [103]:
obesity_data.loc[0, 'Age'] = np.nan
obesity_data.loc[0, 'SMOKE'] = np.nan
obesity_data.loc[2, 'family_history'] = np.nan
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,NaN,1.62,24.386526,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.5,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.5,1.60,30.078125,77.0,NaN,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.5,1.60,33.984375,0.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.0,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [104]:
obesity_data['Age'] = obesity_data['Age'].fillna(obesity_data['Age'].mean())
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,36.471255,1.62,24.386526,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.500000,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.500000,1.60,30.078125,77.0,NaN,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.500000,1.60,33.984375,0.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.000000,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [105]:
obesity_data.fillna({'SMOKE' : 'unknown', 'family_history': 'No'}, inplace=True)
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,36.471255,1.62,24.386526,64.0,yes,no,2.0,3.0,unknown,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.500000,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.500000,1.60,30.078125,77.0,No,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,40.500000,1.60,33.984375,0.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.000000,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [106]:
obesity_data.loc[3, 'Age'] = np.nan
obesity_data.loc[0, 'SMOKE'] = np.nan
obesity_data.loc[2, 'family_history'] = np.nan
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,36.471255,1.62,24.386526,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.500000,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.500000,1.60,30.078125,77.0,NaN,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,NaN,1.60,33.984375,0.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.000000,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [107]:
obesity_data['Age'] = obesity_data['Age'].fillna(obesity_data['Age'].interpolate())
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
0,Female,36.471255,1.62,24.386526,64.0,yes,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Overrrr Weight,Young
1,Female,31.500000,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
2,Not Preferred to say,34.500000,1.60,30.078125,77.0,NaN,no,2.0,3.0,doesn`t matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Young
3,Male,33.750000,1.60,33.984375,0.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.000000,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young

In [108]:
obesity_data.dropna(inplace=True)
obesity_data.head()

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
1,Female,31.50,1.52,24.238227,56.0,no data,no,3.0,3.0,doesn`t matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Young
3,Male,33.75,1.60,33.984375,0.0,no,no,3.0,3.0,doesn`t matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.00,1.78,28.342381,89.8,no,no,2.0,1.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Young
5,Male,43.50,1.62,20.195092,53.0,0,yes,2.0,3.0,doesn`t matter,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not Young
6,Female,34.50,1.50,24.444444,55.0,yes,yes,3.0,3.0,doesn`t matter,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Young

In [109]:
obesity_data.dropna(axis = 1)

,Gender,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
1,Female,31.500000,1.520000,24.238227,56.000000,no data,no,3.0,3.0,doesn`t matter,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,Young
3,Male,33.750000,1.600000,33.984375,0.000000,no,no,3.0,3.0,doesn`t matter,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,Not Young
4,Male,33.000000,1.780000,28.342381,89.800000,no,no,2.0,1.0,doesn`t matter,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,Young
5,Male,43.500000,1.620000,20.195092,53.000000,0,yes,2.0,3.0,doesn`t matter,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight,Not Young
6,Female,34.500000,1.500000,24.444444,55.000000,yes,yes,3.0,3.0,doesn`t matter,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight,Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,31.465263,1.710730,44.901475,131.408528,yes,yes,3.0,3.0,doesn`t matter,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,Young
2107,Female,32.974413,1.748584,43.741923,133.742943,yes,yes,3.0,3.0,doesn`t matter,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,Young
2108,Female,33.786054,1.752206,43.543817,133.689352,yes,yes,3.0,3.0,doesn`t matter,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,Young
2109,Female,36.542904,1.739450,44.071535,133.346641,yes,yes,3.0,3.0,doesn`t matter,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,Not Young
2110,Female,35.497063,1.738836,44.144338,133.472641,yes,yes,3.0,3.0,doesn`t matter,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,Not Young

In [110]:
obesity_data.groupby('Gender').count()

,Age,Height,BMI,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category,Age Category
Gender,,,,,,,,,,,,,,,,,
Female,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042
Male,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067

In [111]:
obesity_data.groupby('Gender')['Height'].mean()

Gender
Female    1.643320
Male      1.758464
Name: Height, dtype: float64

In [113]:
obesity_data.groupby('Gender')['Age'].median()

Gender
Female    33.0
Male      34.5
Name: Age, dtype: float64

In [114]:
obesity_data.groupby('Gender').agg({'Height' : 'mean', 'Age' : 'median'})

          Height   Age
Gender
Female  1.643320  33.0
Male    1.758464  34.5